import type { Metadata } from "next";
import Header from "../components/common/Header/Header";

export const metadata: Metadata = {
  title: "Mango Traceability System",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <Header />
      <div className="flex">
        {children}
      </div>
    </div>
  );
}
