import type { Metadata } from "next";
import Sidebar from "../components/admin/Sidebar";

export const metadata: Metadata = {
  title: "Mango Traceability System",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <div className="flex">
        <Sidebar />
        {children}
      </div>
    </div>
  );
}
