import type { Metadata } from "next";
import "../../styles/style.css";

export const metadata: Metadata = {
  title: "Register-New-Farm - Mango Traceability System",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <div>{children}</div>
    </div>
  );
}
