import type { Metadata } from "next";
import ReduxProvider from "@/store/redux-provider";
import { Funnel_Display } from "next/font/google";
import Header from "./components/Header/Header";
import "./globals.css";
import "../styles/style.css";

const funnel = Funnel_Display({
  variable: "--font-funnel-display",
});

export const metadata: Metadata = {
  title: "Mango Traceability System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={`${funnel.className} antialiased`}>
          <Header />
          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
