import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";

const funnel = Funnel_Display({
  variable: "--font-funnel-display",
});

export const metadata: Metadata = {
  title: "Mango Traceability System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${funnel.className} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
