import type { Metadata } from "next";
// CSS is handled by Next.js; it has no TypeScript module declaration.
// @ts-expect-error -- intentional side-effect import for global styles
import "../../styles/style.css";
import Login_Header from "../components/common/Header/Login_Header";

export const metadata: Metadata = {
  title: "Login - Mango Traceability System",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-[100vh] overflow-y-auto relative bg-[url(/assets/login-bg.jpg)] bg-cover bg-bottom bg-no-repeat flex flex-col items-center justify-center">
      <Login_Header />
      <div>{children}</div>
    </div>
  );
}
